load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_library"
)

cc_library(
      name       = "aapFunctionalCluster_Firewall"
   ,  srcs       = ["aapFunctionalCluster_Firewall.cpp"]
#  ,  deps       = ["//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"]
   ,  hdrs       = [
            "interface_Firewall_FirewallStateSwitch.hpp"
      ]
   ,  includes   = ["."]
   ,  visibility = ["//visibility:public"]
)

